### PR TITLE
Using blobhash()

### PR DESCRIPTION
**Pull request by qzhodl**
Try to fix https://github.com/ethstorage/storage-contracts-v1/issues/62

### CODE REVIEW

**Comment by syntrust** [comment]
Gas usage of `putBlob`:
before using blobhash(): first blob 117,274, later 98074
after using blobhash():  first 110,306. later 93187

**Review by syntrust — APPROVED** [review]

**Review by qizhou — APPROVED** [review]
Nice!

**Comment by qizhou** [comment]
> Gas usage of `putBlob`: before using blobhash(): first blob 117,274, later 98074 after using blobhash(): first 110,306. later 93187

I am a bit surprised about the gas cost.  Do you have the contract and tx deploy on testnets?

**Comment by qzhodl** [comment]
> > Gas usage of `putBlob`: before using blobhash(): first blob 117,274, later 98074 after using blobhash(): first 110,306. later 93187
> 
> I am a bit surprised about the gas cost. Do you have the contract and tx deploy on testnets?

Here is a gas profile for `pubBlob`: https://dashboard.tenderly.co/tx/goerli/0xbb283594dd1129dfcaaa35f5cc04d10af02759454a894162ab47aa05317897fe/gas-usage

**Comment by qizhou** [comment]
An optimization is proposed here https://github.com/ethstorage/storage-contracts-v1/issues/70

**Comment by qzhodl** [comment]
> An optimization is proposed here #70

Storage contract is a proxy implementation, so its constructor can't accept any parameters, and that's why we don't use immutable

**Comment by qizhou** [comment]
An idea is to use ClonesWithImmutableArgs.sol (employed by OP) https://goerli.etherscan.io/address/0x666C3d298B9c360990F901b3Eded4e7a9d7AD446#code#F2#L5

**Pull request merged**
